/**
 * Week 2 shadow signals: re-analyze cohort with 4 new signals (extraction only), then write report.
 * Reads data/week2-cohort.json, runs evaluateBatch for each profile, saves profiles, aggregates shadow
 * stats and evidence, writes docs/week2-shadow-signals.md.
 *
 * Run: npm run reanalyze-week2
 */

import { createHash } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { NestFactory } from '@nestjs/core';
import { AppModule } from '../src/app.module';
import type { EvaluateBatchResult } from '../src/evaluate/evaluate.service';
import { EvaluateService } from '../src/evaluate/evaluate.service';
import { ProfilesJsonService } from '../src/profiles/profiles-json.service';
import { SHADOW_SIGNAL_KEYS } from '../src/extraction/extracted-signals.interface';
import type { ExtractedSignals } from '../src/extraction/extracted-signals.interface';
import type { ProfileJsonPayload } from '../src/profiles/profiles-json.service';

const ROOT = process.cwd();
const COHORT_PATH = join(ROOT, 'data', 'week2-cohort.json');
const REPORT_PATH = join(ROOT, 'docs', 'week2-shadow-signals.md');
if (!process.env.PROFILES_DATA_DIR) {
  process.env.PROFILES_DATA_DIR = join(ROOT, 'data', 'profiles');
}
const PROMPT_VERSION = 'v1';
const POLICY_VERSION = 'product-score-v1';

function hashText(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex').slice(0, 16);
}

function aggregateShadow(profiles: ProfileJsonPayload[]): Map<string, { nonNullCount: number; totalSlots: number; evidence: { quote: string; domain: string; profileId: string; value: number }[] }> {
  const agg = new Map<string, { nonNullCount: number; totalSlots: number; evidence: { quote: string; domain: string; profileId: string; value: number }[] }>();
  const domainCount = profiles.length * 3;

  for (const key of SHADOW_SIGNAL_KEYS) {
    agg.set(key, { nonNullCount: 0, totalSlots: domainCount, evidence: [] });
  }

  for (const profile of profiles) {
    if (!profile.evaluation) continue;
    const domains: { domain: string; data: ExtractedSignals }[] = [
      { domain: 'self', data: profile.evaluation.self },
      { domain: 'relationship', data: profile.evaluation.relationship },
      { domain: 'partner', data: profile.evaluation.partner },
    ];
    for (const { domain, data } of domains) {
      for (const key of SHADOW_SIGNAL_KEYS) {
        const a = agg.get(key)!;
        const value = data.signals[key];
        if (value != null) {
          a.nonNullCount += 1;
          const ev = (data.evidence ?? []).find((e) => e.signal === key);
          if (ev && a.evidence.length < 5) {
            a.evidence.push({ quote: ev.quote, domain, profileId: profile.id, value });
          }
        }
      }
    }
  }
  return agg;
}

function buildReport(
  agg: Map<string, { nonNullCount: number; totalSlots: number; evidence: { quote: string; domain: string; profileId: string; value: number }[] }>,
  processed: number,
): string {
  const lines: string[] = [
    '# Week 2 shadow signals report',
    '',
    'Generated by `npm run reanalyze-week2`. Cohort re-analyzed with 4 new signals in **shadow mode** (extraction only; not wired into compatibility, friction, or finalScore).',
    '',
    '## Cohort',
    '',
    `- Profiles processed: ${processed}`,
    `- Total domain extractions (self + relationship + partner): ${processed * 3}`,
    '',
    '## Non-null rate per new signal',
    '',
    '| Signal | Non-null | Total slots | Rate % |',
    '|--------|----------|-------------|--------|',
  ];

  for (const key of SHADOW_SIGNAL_KEYS) {
    const a = agg.get(key)!;
    const pct = a.totalSlots > 0 ? ((a.nonNullCount / a.totalSlots) * 100).toFixed(1) : '0';
    lines.push(`| ${key} | ${a.nonNullCount} | ${a.totalSlots} | ${pct} |`);
  }

  lines.push('', '## Evidence examples (3–5 per signal)', '');

  for (const key of SHADOW_SIGNAL_KEYS) {
    const a = agg.get(key)!;
    lines.push(`### ${key}`, '');
    if (a.evidence.length === 0) {
      lines.push('*No evidence collected.*', '');
    } else {
      for (const e of a.evidence) {
        lines.push(`- **${e.profileId}** (${e.domain}, value=${e.value}): "${e.quote}"`);
      }
    }
    lines.push('');
  }

  lines.push('## Overlap risk with existing signals', '');
  lines.push('- **conflictStyle** vs directness: both relate to communication; conflictStyle is conflict-specific. Review evidence for double-counting.', '');
  lines.push('- **noveltyVsRoutine** vs lifestylePace: novelty is variety vs repetition; pace is speed. Some phrases ("spontaneous", "calm") may trigger both.', '');
  lines.push('- **intellectualCuriosity** vs emotionalDepth: curiosity = ideas/learning; depth = emotional openness. Distinct; low overlap risk.', '');
  lines.push('- **structureChaosTolerance** vs noveltyVsRoutine: structure = plans vs improv; novelty = new vs same. Some overlap ("spontaneous", "go with the flow").', '');
  lines.push('', '## Noise / hallucination risk', '');
  lines.push('- If evidence quotes are generic or not present in source text → hallucination.', '');
  lines.push('- If non-null rate is very high with short profiles → possible over-inference.', '');
  lines.push('- Manual spot-check of evidence above recommended.', '');
  lines.push('', '## Recommendation per signal', '');
  lines.push('| Signal | Recommendation | Notes |', '|--------|----------------|-------|');
  for (const key of SHADOW_SIGNAL_KEYS) {
    lines.push(`| ${key} | TBD (KEEP / KEEP_LATER / DROP) | Fill after review |`);
  }
  lines.push('');
  return lines.join('\n');
}

async function main(): Promise<void> {
  let cohortIds: string[];
  try {
    const raw = await readFile(COHORT_PATH, 'utf8');
    cohortIds = JSON.parse(raw) as string[];
    if (!Array.isArray(cohortIds) || cohortIds.some((id) => typeof id !== 'string')) {
      throw new Error('week2-cohort.json must be a JSON array of profile ID strings');
    }
  } catch (err) {
    console.error('Failed to read cohort:', COHORT_PATH, err);
    process.exit(1);
  }

  const app = await NestFactory.createApplicationContext(AppModule, { logger: false });
  const evaluateService = app.get(EvaluateService);
  const profilesJson = app.get(ProfilesJsonService);

  let processed = 0;
  let failed = 0;
  const updatedProfiles: ProfileJsonPayload[] = [];

  for (const id of cohortIds) {
    const profile = await profilesJson.getById(id);
    if (!profile) {
      console.warn(`Profile not found: ${id}`);
      failed++;
      continue;
    }

    const textConcat =
      (profile.texts.aboutMe ?? '') +
      '|' +
      (profile.texts.aboutPartner ?? '') +
      '|' +
      (profile.texts.aboutRelationship ?? '');
    const textHash = hashText(textConcat);

    try {
      const { result: evaluation } = await evaluateService.evaluateBatch({
        aboutMe: profile.texts.aboutMe ?? '',
        aboutRelationship: profile.texts.aboutRelationship ?? '',
        aboutPartner: profile.texts.aboutPartner ?? '',
      });

      processed++;
      const updatedAt = new Date().toISOString();
      const policyVersionSaved = evaluation.productScores?.policyVersion ?? POLICY_VERSION;

      await profilesJson.save(profile.id, {
        id: profile.id,
        name: profile.name,
        texts: profile.texts,
        evaluation: evaluation as EvaluateBatchResult,
        evaluationStatus: 'DONE',
        evaluatedAt: updatedAt,
        promptVersion: PROMPT_VERSION,
        policyVersion: policyVersionSaved,
        textHash,
        signals: evaluation.self.signals,
      });

      updatedProfiles.push({
        ...profile,
        evaluation: evaluation as EvaluateBatchResult,
      });
    } catch (err) {
      console.error(`Analyze failed for ${id}:`, err);
      failed++;
    }
  }

  const agg = aggregateShadow(updatedProfiles);
  const report = buildReport(agg, processed);

  try {
    await mkdir(join(ROOT, 'docs'), { recursive: true });
    await writeFile(REPORT_PATH, report, 'utf8');
    console.log(`Report written: ${REPORT_PATH}`);
  } catch (err) {
    console.error('Failed to write report:', REPORT_PATH, err);
  }

  await app.close();

  console.log('');
  console.log('--- Week 2 reanalyze report ---');
  console.log('Processed:', processed);
  console.log('Failed:', failed);
  console.log('Report:', REPORT_PATH);
  console.log('');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
