/**
 * Sprint 41 Story 3 — shared IDs + candidate catalog for validation seed/verify.
 * Prefix `s41val_` is required for scoped cleanup.
 */

export const S41_PREFIX = 's41val_';
export const EVAL_VERSION = 'sprint41-validation-v1';

export const VIEWER_A = {
  userId: 's41val_user_viewer_a',
  profileId: 's41val_prof_viewer_a',
  sessionId: 's41val_sess_viewer_a',
  rawSessionToken: 's41val-viewer-a-session-token-fixed-01',
  name: 'Alex Rivera',
  nickname: 's41val_alex',
  email: 's41val-viewer-a@bondit-test.local',
  birthDate: '1994-03-12',
  aboutMe:
    'Product engineer who wants kids and a partner who cares about growth and weekends outdoors.',
  wantsChildren: 'YES',
  interests: ['tech', 'hiking', 'cooking', 'travel'],
} as const;

export const VIEWER_B = {
  userId: 's41val_user_viewer_b',
  profileId: 's41val_prof_viewer_b',
  sessionId: 's41val_sess_viewer_b',
  rawSessionToken: 's41val-viewer-b-session-token-fixed-01',
  name: 'Jordan Lee',
  nickname: 's41val_jordan',
  email: 's41val-viewer-b@bondit-test.local',
  birthDate: '1997-07-22',
  aboutMe:
    'Designer who wants kids eventually and values emotional honesty over small talk.',
  wantsChildren: 'YES',
  interests: ['design', 'yoga', 'museums', 'cooking'],
} as const;

export type S41Tier = 'HIGH' | 'GOOD' | 'OTHER';

export type S41CandidateDef = {
  key: string;
  profileId: string;
  userId: string;
  photoId: string;
  rankId: string;
  name: string;
  nickname: string;
  email: string;
  birthDate: string;
  ageApprox: number;
  matchScore: number;
  tier: S41Tier;
  wantsChildren: 'YES' | 'UNSURE' | 'NO';
  interests: string[];
  industry: string;
  aboutMe: string;
  /** RGB tint for distinct local placeholder photo */
  photoRgb: [number, number, number];
};

/** Female pool for Viewer A (male seeking female). Scores locked for 2/4/4 tiers. */
export const CANDIDATES_FOR_VIEWER_A: S41CandidateDef[] = [
  {
    key: 'f01',
    profileId: 's41val_prof_cand_f01',
    userId: 's41val_user_cand_f01',
    photoId: 's41val_photo_cand_f01',
    rankId: 's41val_rank_a_f01',
    name: 'Sarah Chen',
    nickname: 's41val_sarah',
    email: 's41val-cand-f01@bondit-test.local',
    birthDate: '1996-05-18',
    ageApprox: 30,
    matchScore: 92,
    tier: 'HIGH',
    wantsChildren: 'YES',
    interests: ['tech', 'hiking', 'cooking'],
    industry: 'tech',
    aboutMe:
      'Backend engineer who wants kids and weekend hikes. Looking for a grounded long-term partner.',
    photoRgb: [220, 90, 110],
  },
  {
    key: 'f02',
    profileId: 's41val_prof_cand_f02',
    userId: 's41val_user_cand_f02',
    photoId: 's41val_photo_cand_f02',
    rankId: 's41val_rank_a_f02',
    name: 'Maya Patel',
    nickname: 's41val_maya',
    email: 's41val-cand-f02@bondit-test.local',
    birthDate: '1998-11-02',
    ageApprox: 28,
    matchScore: 88,
    tier: 'HIGH',
    wantsChildren: 'YES',
    interests: ['travel', 'cooking', 'running'],
    industry: 'product',
    aboutMe:
      'PM who wants kids, loves travel planning, and cares about shared values more than status.',
    photoRgb: [90, 140, 220],
  },
  {
    key: 'f03',
    profileId: 's41val_prof_cand_f03',
    userId: 's41val_user_cand_f03',
    photoId: 's41val_photo_cand_f03',
    rankId: 's41val_rank_a_f03',
    name: 'Rachel Kim',
    nickname: 's41val_rachel',
    email: 's41val-cand-f03@bondit-test.local',
    birthDate: '1995-01-30',
    ageApprox: 31,
    matchScore: 78,
    tier: 'GOOD',
    wantsChildren: 'YES',
    interests: ['yoga', 'museums', 'cooking'],
    industry: 'creative',
    aboutMe: 'Creative director who wants kids and quieter evenings after busy weeks.',
    photoRgb: [120, 180, 100],
  },
  {
    key: 'f04',
    profileId: 's41val_prof_cand_f04',
    userId: 's41val_user_cand_f04',
    photoId: 's41val_photo_cand_f04',
    rankId: 's41val_rank_a_f04',
    name: 'Nina Alvarez',
    nickname: 's41val_nina',
    email: 's41val-cand-f04@bondit-test.local',
    birthDate: '1997-08-14',
    ageApprox: 29,
    matchScore: 76,
    tier: 'GOOD',
    wantsChildren: 'UNSURE',
    interests: ['hiking', 'photography', 'coffee'],
    industry: 'outdoors',
    aboutMe: 'Trail runner open to kids someday; values honesty and shared adventures.',
    photoRgb: [200, 150, 60],
  },
  {
    key: 'f05',
    profileId: 's41val_prof_cand_f05',
    userId: 's41val_user_cand_f05',
    photoId: 's41val_photo_cand_f05',
    rankId: 's41val_rank_a_f05',
    name: 'Lena Brooks',
    nickname: 's41val_lena',
    email: 's41val-cand-f05@bondit-test.local',
    birthDate: '1994-12-09',
    ageApprox: 32,
    matchScore: 74,
    tier: 'GOOD',
    wantsChildren: 'YES',
    interests: ['books', 'cooking', 'boardgames'],
    industry: 'education',
    aboutMe: 'Teacher who wants kids and a partner who shows up for weeknight dinners.',
    photoRgb: [160, 100, 180],
  },
  {
    key: 'f06',
    profileId: 's41val_prof_cand_f06',
    userId: 's41val_user_cand_f06',
    photoId: 's41val_photo_cand_f06',
    rankId: 's41val_rank_a_f06',
    name: 'Ava Nguyen',
    nickname: 's41val_ava',
    email: 's41val-cand-f06@bondit-test.local',
    birthDate: '1999-04-21',
    ageApprox: 27,
    matchScore: 72,
    tier: 'GOOD',
    wantsChildren: 'UNSURE',
    interests: ['tech', 'music', 'startups'],
    industry: 'tech',
    aboutMe: 'Startup marketer; open on kids; wants intellectual spark and kindness.',
    photoRgb: [70, 170, 170],
  },
  {
    key: 'f07',
    profileId: 's41val_prof_cand_f07',
    userId: 's41val_user_cand_f07',
    photoId: 's41val_photo_cand_f07',
    rankId: 's41val_rank_a_f07',
    name: 'Dana Morris',
    nickname: 's41val_dana',
    email: 's41val-cand-f07@bondit-test.local',
    birthDate: '1999-09-03',
    ageApprox: 27,
    matchScore: 62,
    tier: 'OTHER',
    wantsChildren: 'UNSURE',
    interests: ['nightlife', 'fashion', 'travel'],
    industry: 'fashion',
    aboutMe:
      'Photogenic, fun, always booked — different life rhythm; great photos, thinner value overlap.',
    photoRgb: [230, 120, 180],
  },
  {
    key: 'f08',
    profileId: 's41val_prof_cand_f08',
    userId: 's41val_user_cand_f08',
    photoId: 's41val_photo_cand_f08',
    rankId: 's41val_rank_a_f08',
    name: 'Zoe Hart',
    nickname: 's41val_zoe',
    email: 's41val-cand-f08@bondit-test.local',
    birthDate: '1998-02-27',
    ageApprox: 28,
    matchScore: 58,
    tier: 'OTHER',
    wantsChildren: 'NO',
    interests: ['climbing', 'dogs', 'craftbeer'],
    industry: 'outdoors',
    aboutMe: 'Clear no on kids; loves climbing and casual dating energy.',
    photoRgb: [100, 110, 130],
  },
  {
    key: 'f09',
    profileId: 's41val_prof_cand_f09',
    userId: 's41val_user_cand_f09',
    photoId: 's41val_photo_cand_f09',
    rankId: 's41val_rank_a_f09',
    name: 'Iris Cole',
    nickname: 's41val_iris',
    email: 's41val-cand-f09@bondit-test.local',
    birthDate: '2000-06-11',
    ageApprox: 26,
    matchScore: 52,
    tier: 'OTHER',
    wantsChildren: 'NO',
    interests: ['parties', 'dj', 'festivals'],
    industry: 'entertainment',
    aboutMe: 'Nightlife-first lifestyle; not looking for the same timeline.',
    photoRgb: [180, 80, 60],
  },
  {
    key: 'f10',
    profileId: 's41val_prof_cand_f10',
    userId: 's41val_user_cand_f10',
    photoId: 's41val_photo_cand_f10',
    rankId: 's41val_rank_a_f10',
    name: 'Quinn Blake',
    nickname: 's41val_quinn_f',
    email: 's41val-cand-f10@bondit-test.local',
    birthDate: '1993-10-19',
    ageApprox: 33,
    matchScore: 48,
    tier: 'OTHER',
    wantsChildren: 'NO',
    interests: ['finance', 'golf', 'wine'],
    industry: 'finance',
    aboutMe: 'Career-max mode; polite but mismatched goals and pace.',
    photoRgb: [80, 90, 100],
  },
];

/** Male pool for Viewer B (female seeking male). Same score/tier mix. */
export const CANDIDATES_FOR_VIEWER_B: S41CandidateDef[] = [
  {
    key: 'm01',
    profileId: 's41val_prof_cand_m01',
    userId: 's41val_user_cand_m01',
    photoId: 's41val_photo_cand_m01',
    rankId: 's41val_rank_b_m01',
    name: 'Noah Kim',
    nickname: 's41val_noah',
    email: 's41val-cand-m01@bondit-test.local',
    birthDate: '1995-04-08',
    ageApprox: 31,
    matchScore: 92,
    tier: 'HIGH',
    wantsChildren: 'YES',
    interests: ['design', 'cooking', 'yoga'],
    industry: 'tech',
    aboutMe:
      'Engineer who wants kids and quiet creative evenings — strong alignment with Jordan.',
    photoRgb: [60, 100, 200],
  },
  {
    key: 'm02',
    profileId: 's41val_prof_cand_m02',
    userId: 's41val_user_cand_m02',
    photoId: 's41val_photo_cand_m02',
    rankId: 's41val_rank_b_m02',
    name: 'Ethan Ruiz',
    nickname: 's41val_ethan',
    email: 's41val-cand-m02@bondit-test.local',
    birthDate: '1996-09-15',
    ageApprox: 30,
    matchScore: 88,
    tier: 'HIGH',
    wantsChildren: 'YES',
    interests: ['museums', 'cooking', 'running'],
    industry: 'creative',
    aboutMe: 'Architect who wants kids and honest conversations after work.',
    photoRgb: [40, 160, 120],
  },
  {
    key: 'm03',
    profileId: 's41val_prof_cand_m03',
    userId: 's41val_user_cand_m03',
    photoId: 's41val_photo_cand_m03',
    rankId: 's41val_rank_b_m03',
    name: 'Liam Park',
    nickname: 's41val_liam',
    email: 's41val-cand-m03@bondit-test.local',
    birthDate: '1994-02-01',
    ageApprox: 32,
    matchScore: 78,
    tier: 'GOOD',
    wantsChildren: 'YES',
    interests: ['yoga', 'books', 'coffee'],
    industry: 'education',
    aboutMe: 'Counselor who wants kids; values emotional depth.',
    photoRgb: [140, 120, 90],
  },
  {
    key: 'm04',
    profileId: 's41val_prof_cand_m04',
    userId: 's41val_user_cand_m04',
    photoId: 's41val_photo_cand_m04',
    rankId: 's41val_rank_b_m04',
    name: 'Owen Hale',
    nickname: 's41val_owen',
    email: 's41val-cand-m04@bondit-test.local',
    birthDate: '1998-12-20',
    ageApprox: 28,
    matchScore: 76,
    tier: 'GOOD',
    wantsChildren: 'UNSURE',
    interests: ['hiking', 'photography', 'dogs'],
    industry: 'outdoors',
    aboutMe: 'Outdoor guide; unsure on kids timing; kind and steady.',
    photoRgb: [110, 150, 70],
  },
  {
    key: 'm05',
    profileId: 's41val_prof_cand_m05',
    userId: 's41val_user_cand_m05',
    photoId: 's41val_photo_cand_m05',
    rankId: 's41val_rank_b_m05',
    name: 'Caleb Orth',
    nickname: 's41val_caleb',
    email: 's41val-cand-m05@bondit-test.local',
    birthDate: '1993-07-07',
    ageApprox: 33,
    matchScore: 74,
    tier: 'GOOD',
    wantsChildren: 'YES',
    interests: ['cooking', 'boardgames', 'jazz'],
    industry: 'hospitality',
    aboutMe: 'Chef who wants kids and shared Sunday meals.',
    photoRgb: [190, 100, 80],
  },
  {
    key: 'm06',
    profileId: 's41val_prof_cand_m06',
    userId: 's41val_user_cand_m06',
    photoId: 's41val_photo_cand_m06',
    rankId: 's41val_rank_b_m06',
    name: 'Miles Grant',
    nickname: 's41val_miles',
    email: 's41val-cand-m06@bondit-test.local',
    birthDate: '1999-01-25',
    ageApprox: 27,
    matchScore: 72,
    tier: 'GOOD',
    wantsChildren: 'UNSURE',
    interests: ['music', 'startups', 'design'],
    industry: 'tech',
    aboutMe: 'Indie founder; open on kids; curious and a bit chaotic.',
    photoRgb: [80, 130, 190],
  },
  {
    key: 'm07',
    profileId: 's41val_prof_cand_m07',
    userId: 's41val_user_cand_m07',
    photoId: 's41val_photo_cand_m07',
    rankId: 's41val_rank_b_m07',
    name: 'Jasper Vale',
    nickname: 's41val_jasper',
    email: 's41val-cand-m07@bondit-test.local',
    birthDate: '1997-05-16',
    ageApprox: 29,
    matchScore: 62,
    tier: 'OTHER',
    wantsChildren: 'UNSURE',
    interests: ['nightlife', 'fashion', 'cars'],
    industry: 'entertainment',
    aboutMe:
      'Model-adjacent social butterfly — great look, thinner values overlap (attractive OTHER).',
    photoRgb: [210, 160, 140],
  },
  {
    key: 'm08',
    profileId: 's41val_prof_cand_m08',
    userId: 's41val_user_cand_m08',
    photoId: 's41val_photo_cand_m08',
    rankId: 's41val_rank_b_m08',
    name: 'Theo Nash',
    nickname: 's41val_theo',
    email: 's41val-cand-m08@bondit-test.local',
    birthDate: '1998-08-30',
    ageApprox: 28,
    matchScore: 58,
    tier: 'OTHER',
    wantsChildren: 'NO',
    interests: ['climbing', 'craftbeer', 'gaming'],
    industry: 'outdoors',
    aboutMe: 'Clear no on kids; climbing first.',
    photoRgb: [90, 95, 110],
  },
  {
    key: 'm09',
    profileId: 's41val_prof_cand_m09',
    userId: 's41val_user_cand_m09',
    photoId: 's41val_photo_cand_m09',
    rankId: 's41val_rank_b_m09',
    name: 'Rex Dillon',
    nickname: 's41val_rex',
    email: 's41val-cand-m09@bondit-test.local',
    birthDate: '2000-03-04',
    ageApprox: 26,
    matchScore: 52,
    tier: 'OTHER',
    wantsChildren: 'NO',
    interests: ['parties', 'dj', 'festivals'],
    industry: 'entertainment',
    aboutMe: 'Festival circuit lifestyle; different timeline.',
    photoRgb: [170, 70, 50],
  },
  {
    key: 'm10',
    profileId: 's41val_prof_cand_m10',
    userId: 's41val_user_cand_m10',
    photoId: 's41val_photo_cand_m10',
    rankId: 's41val_rank_b_m10',
    name: 'Victor Shaw',
    nickname: 's41val_victor',
    email: 's41val-cand-m10@bondit-test.local',
    birthDate: '1992-11-28',
    ageApprox: 34,
    matchScore: 48,
    tier: 'OTHER',
    wantsChildren: 'NO',
    interests: ['finance', 'golf', 'wine'],
    industry: 'finance',
    aboutMe: 'Career-first; polite mismatch on goals.',
    photoRgb: [70, 75, 85],
  },
];

export const ALL_CANDIDATES = [
  ...CANDIDATES_FOR_VIEWER_A,
  ...CANDIDATES_FOR_VIEWER_B,
];

export const ALL_PROFILE_IDS = [
  VIEWER_A.profileId,
  VIEWER_B.profileId,
  ...ALL_CANDIDATES.map((c) => c.profileId),
];

export const ALL_USER_IDS = [
  VIEWER_A.userId,
  VIEWER_B.userId,
  ...ALL_CANDIDATES.map((c) => c.userId),
];
