/**
 * Stable UI-side codes for product observability (browser console JSON).
 * Keep values stable for grep and future log aggregation.
 */
export const UiErrorCodes = {
  UI_AUTH_BOOTSTRAP: 'UI_AUTH_BOOTSTRAP',
  UI_AUTH_ME_OK: 'UI_AUTH_ME_OK',
  UI_AUTH_ME_UNAUTHORIZED: 'UI_AUTH_ME_UNAUTHORIZED',
  UI_AUTH_ME_FORBIDDEN: 'UI_AUTH_ME_FORBIDDEN',
  UI_AUTH_ME_NETWORK: 'UI_AUTH_ME_NETWORK',
  UI_AUTH_ME_UNEXPECTED: 'UI_AUTH_ME_UNEXPECTED',
  UI_LOGIN_CREDENTIAL_START: 'UI_LOGIN_CREDENTIAL_START',
  UI_AUTH_GOOGLE_EXCHANGE_OK: 'UI_AUTH_GOOGLE_EXCHANGE_OK',
  UI_AUTH_GOOGLE_EXCHANGE_FAIL: 'UI_AUTH_GOOGLE_EXCHANGE_FAIL',
  UI_AUTH_LOGOUT_OK: 'UI_AUTH_LOGOUT_OK',
  UI_AUTH_LOGOUT_FAIL: 'UI_AUTH_LOGOUT_FAIL',
  UI_AUTH_LOGOUT_NETWORK: 'UI_AUTH_LOGOUT_NETWORK',
  UI_PROFILE_GET_OK: 'UI_PROFILE_GET_OK',
  UI_PROFILE_GET_EMPTY: 'UI_PROFILE_GET_EMPTY',
  UI_PROFILE_GET_FAIL: 'UI_PROFILE_GET_FAIL',
  UI_PROFILE_GET_NETWORK: 'UI_PROFILE_GET_NETWORK',
  UI_PROFILE_CREATE_OK: 'UI_PROFILE_CREATE_OK',
  UI_PROFILE_CREATE_FAIL: 'UI_PROFILE_CREATE_FAIL',
  UI_PROFILE_CREATE_NETWORK: 'UI_PROFILE_CREATE_NETWORK',
  UI_PROFILE_PATCH_OK: 'UI_PROFILE_PATCH_OK',
  UI_PROFILE_PATCH_FAIL: 'UI_PROFILE_PATCH_FAIL',
  UI_PROFILE_PATCH_NETWORK: 'UI_PROFILE_PATCH_NETWORK',
  UI_PROFILE_SUBMIT_OK: 'UI_PROFILE_SUBMIT_OK',
  UI_PROFILE_SUBMIT_FAIL: 'UI_PROFILE_SUBMIT_FAIL',
  UI_PROFILE_SUBMIT_NETWORK: 'UI_PROFILE_SUBMIT_NETWORK',
  UI_PROFILE_ANALYSIS_LATEST_OK: 'UI_PROFILE_ANALYSIS_LATEST_OK',
  UI_PROFILE_ANALYSIS_LATEST_FAIL: 'UI_PROFILE_ANALYSIS_LATEST_FAIL',
  UI_PROFILE_ANALYSIS_LATEST_NETWORK: 'UI_PROFILE_ANALYSIS_LATEST_NETWORK',
  UI_MIDDLEWARE_AUTH_REDIRECT: 'UI_MIDDLEWARE_AUTH_REDIRECT',
  UI_RENDER_FATAL: 'UI_RENDER_FATAL',
  DATING_ROUTE_ERROR: 'DATING_ROUTE_ERROR',
  AUTHENTICATED_ROUTE_ERROR: 'AUTHENTICATED_ROUTE_ERROR',
} as const;

export type UiErrorCode = (typeof UiErrorCodes)[keyof typeof UiErrorCodes];
